# GitHub Actions Runner Controller (ARC) - Controller Manager
#
# This deployment is configured to run on system nodes (workload-type: system)
# for cost-efficient 24/7 operation. The controller manages the lifecycle of
# runner scale sets and listeners.
#
# This is typically deployed via Helm chart: gha-rs-controller
# helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
# helm install arc actions-runner-controller/gha-rs-controller -n eks-arc-systems
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-gha-rs-controller
  namespace: eks-arc-systems
  labels:
    actions.github.com/controller-service-account-name: arc-gha-rs-controller
    actions.github.com/controller-service-account-namespace: eks-arc-systems
    app.kubernetes.io/instance: arc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: eks-arc-systems
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/version: 0.13.0
    helm.sh/chart: gha-rs-controller-0.13.0
  annotations:
    meta.helm.sh/release-name: arc
    meta.helm.sh/release-namespace: eks-arc-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: arc
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/namespace: eks-arc-systems
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: arc
        app.kubernetes.io/name: gha-rs-controller
        app.kubernetes.io/namespace: eks-arc-systems
        app.kubernetes.io/part-of: gha-rs-controller
        app.kubernetes.io/version: 0.13.0
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: arc-gha-rs-controller
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/actions/gha-runner-scale-set-controller:0.13.0
          command:
            - /manager
          args:
            - '--auto-scaling-runner-set-only'
            - '--log-level=debug'
            - '--log-format=text'
            - '--runner-max-concurrent-reconciles=2'
            - '--update-strategy=immediate'
            - '--listener-metrics-addr=0'
            - '--listener-metrics-endpoint='
            - '--metrics-addr=0'
          env:
            - name: CONTROLLER_MANAGER_CONTAINER_IMAGE
              value: ghcr.io/actions/gha-runner-scale-set-controller:0.13.0
            - name: CONTROLLER_MANAGER_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                      - system
      tolerations:
        - key: workload-type
          operator: Equal
          value: system
          effect: NoSchedule
