# AWS Cluster Autoscaler Deployment
#
# This deployment is configured to run on system nodes (workload-type: system)
# for cost-efficient 24/7 operation alongside the ARC listener.
#
# The autoscaler automatically scales your EKS node groups based on pending pods,
# enabling the build-runner nodes to scale to zero when idle.
#
# Before applying, you must:
#   1. Replace {your-region} with your AWS region (e.g., us-east-1)
#   2. Replace {your-cluster-name} with your EKS cluster name
#   3. Ensure the cluster-autoscaler service account has appropriate IAM permissions
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: cluster-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-cluster-autoscaler
    helm.sh/chart: cluster-autoscaler-9.52.1
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    meta.helm.sh/release-name: cluster-autoscaler
    meta.helm.sh/release-namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cluster-autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      priorityClassName: system-cluster-critical
      containers:
        - name: aws-cluster-autoscaler
          image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.34.1
          command:
            - ./cluster-autoscaler
            - '--cloud-provider=aws'
            - '--namespace=kube-system'
            # Replace {your-cluster-name} with your EKS cluster name
            - '--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/{your-cluster-name}'  # <-- REPLACE
            - '--logtostderr=true'
            - '--stderrthreshold=info'
            - '--v=4'
            - '--skip-nodes-with-system-pods=false'
            - '--skip-nodes-with-local-storage=false'
            - '--scale-down-unneeded-time=5m'
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: AWS_REGION
              value: '{your-region}'  # <-- REPLACE (e.g., us-east-1)
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                      - system
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: workload-type
          operator: Equal
          value: system
          effect: NoSchedule
